version: '3'
services:
  postgres:
    image: "postgres:12-alpine"
    volumes:
    - postgres:/var/lib/postgresql/data
    environment: &pgenv
      POSTGRES_USER: discourse
      POSTGRES_PASSWORD: mysecret
  redis:
    image: "redis:5"
    volumes:
    - redis:/data
  puma:
    build: .
    depends_on:
      - postgres
      - redis
    volumes:
    - discourse:/app/shared
    env_file: discourse.env
    environment:
      <<: *pgenv
  sidekiq:
    build: .
    depends_on:
      - puma
    volumes:
    - discourse:/app/shared
    entrypoint: /app/bundle exec sidekiq
    env_file: discourse.env
    environment:
      <<: *pgenv
  caddy:
    build: .
    volumes:
    - discourse:/app/shared
    entrypoint: /app/caddy
    env_file: discourse.env
    ports:
      - "80:3000"

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  discourse:
    driver: local
