version: '3'
services:
  postgres:
    image: "postgres:12-alpine"
    volumes:
    - postgres:/var/lib/postgresql/data
    environment: &pgenv
      POSTGRES_USER: discourse
      POSTGRES_PASSWORD: mysecret
  redis:
    image: "redis:5"
    volumes:
    - redis:/data
  puma:
    image: digineode/discourse:latest
    depends_on:
      - postgres
      - redis
    volumes:
    - discourse:/app/shared
    env_file: discourse.env
    environment:
      <<: *pgenv
  sidekiq:
    image: digineode/discourse:latest
    depends_on:
      - puma
    volumes:
    - discourse:/app/shared
    entrypoint: /app/bundle exec sidekiq --config /app/sidekiq.yml
    env_file: discourse.env
    environment:
      <<: *pgenv
  nginx:
    image: digineode/discourse:latest
    depends_on:
      - puma
    volumes:
    - discourse:/app/shared
    entrypoint: /app/nginx
    env_file: discourse.env
    ports:
      - "3000:80"

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  discourse:
    driver: local
